In [1]:
import numpy as np
import pandas as pd

In [2]:
dict = {
    'Name' : ["Hydrogen", "Helium", "Lithium", "Berrilium", "Boron", "Carbon", "Nitrogen", "Oxygen", "Flourine", "Neon"],
    'Atomic Number' : [ 1, 2 , 3 , 4, 5, 6, 7, 8, 9, 10],
    'Mass Number' : [ 1, 4 , 6, 8, 10, 12, 14, 16, 18, 20 ],
    'Symbol' : [ "H", "He", "li", "Be", "B", "C", "N", "O", "Fl", "Ne"]}

In [3]:
df = pd.DataFrame(dict)

In [4]:
df

        Name  Atomic Number  Mass Number Symbol
0   Hydrogen              1            1      H
1     Helium              2            4     He
2    Lithium              3            6     li
3  Berrilium              4            8     Be
4      Boron              5           10      B
5     Carbon              6           12      C
6   Nitrogen              7           14      N
7     Oxygen              8           16      O
8   Flourine              9           18     Fl
9       Neon             10           20     Ne

In [5]:
df.T

,0,1,2,3,4,5,6,7,8,9
Name,Hydrogen,Helium,Lithium,Berrilium,Boron,Carbon,Nitrogen,Oxygen,Flourine,Neon
Atomic Number,1,2,3,4,5,6,7,8,9,10
Mass Number,1,4,6,8,10,12,14,16,18,20
Symbol,H,He,li,Be,B,C,N,O,Fl,Ne

In [6]:
df

        Name  Atomic Number  Mass Number Symbol
0   Hydrogen              1            1      H
1     Helium              2            4     He
2    Lithium              3            6     li
3  Berrilium              4            8     Be
4      Boron              5           10      B
5     Carbon              6           12      C
6   Nitrogen              7           14      N
7     Oxygen              8           16      O
8   Flourine              9           18     Fl
9       Neon             10           20     Ne

In [7]:
df.index = [1,2,3,4,5,6,7,8,9,10]

In [8]:
df

         Name  Atomic Number  Mass Number Symbol
1    Hydrogen              1            1      H
2      Helium              2            4     He
3     Lithium              3            6     li
4   Berrilium              4            8     Be
5       Boron              5           10      B
6      Carbon              6           12      C
7    Nitrogen              7           14      N
8      Oxygen              8           16      O
9    Flourine              9           18     Fl
10       Neon             10           20     Ne

In [9]:
type(df)

pandas.DataFrame

In [10]:
df.describe

<bound method NDFrame.describe of          Name  Atomic Number  Mass Number Symbol
1    Hydrogen              1            1      H
2      Helium              2            4     He
3     Lithium              3            6     li
4   Berrilium              4            8     Be
5       Boron              5           10      B
6      Carbon              6           12      C
7    Nitrogen              7           14      N
8      Oxygen              8           16      O
9    Flourine              9           18     Fl
10       Neon             10           20     Ne>

In [11]:
df.to_numpy()

array([['Hydrogen', 1, 1, 'H'],
       ['Helium', 2, 4, 'He'],
       ['Lithium', 3, 6, 'li'],
       ['Berrilium', 4, 8, 'Be'],
       ['Boron', 5, 10, 'B'],
       ['Carbon', 6, 12, 'C'],
       ['Nitrogen', 7, 14, 'N'],
       ['Oxygen', 8, 16, 'O'],
       ['Flourine', 9, 18, 'Fl'],
       ['Neon', 10, 20, 'Ne']], dtype=object)

In [12]:
df

         Name  Atomic Number  Mass Number Symbol
1    Hydrogen              1            1      H
2      Helium              2            4     He
3     Lithium              3            6     li
4   Berrilium              4            8     Be
5       Boron              5           10      B
6      Carbon              6           12      C
7    Nitrogen              7           14      N
8      Oxygen              8           16      O
9    Flourine              9           18     Fl
10       Neon             10           20     Ne

In [13]:
df.sort_index(axis = 0, ascending = False)

         Name  Atomic Number  Mass Number Symbol
10       Neon             10           20     Ne
9    Flourine              9           18     Fl
8      Oxygen              8           16      O
7    Nitrogen              7           14      N
6      Carbon              6           12      C
5       Boron              5           10      B
4   Berrilium              4            8     Be
3     Lithium              3            6     li
2      Helium              2            4     He
1    Hydrogen              1            1      H

In [14]:
df

         Name  Atomic Number  Mass Number Symbol
1    Hydrogen              1            1      H
2      Helium              2            4     He
3     Lithium              3            6     li
4   Berrilium              4            8     Be
5       Boron              5           10      B
6      Carbon              6           12      C
7    Nitrogen              7           14      N
8      Oxygen              8           16      O
9    Flourine              9           18     Fl
10       Neon             10           20     Ne

In [15]:
dit = { "Name" : ["Sodium", "Magnesium", "Aluminium", "Silicon", "Phosphorus", "Sulphur", "Chlorine","Argon", "Potassium", "Calcium"],
                            "Atomic number" : [ 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
                            "Mass Number" : [ 22, 24, 26, 28, 30, 32, 34, 36, 38, 40],
                            "Symbol" : [ "Na", "Mg", "Al", "Si", "P", "S", "Cl","Ar", "K", "Ca"]}

In [16]:
import pandas as pd

In [17]:
dif = pd.DataFrame(dit)

In [18]:
dif

         Name  Atomic number  Mass Number Symbol
0      Sodium             11           22     Na
1   Magnesium             12           24     Mg
2   Aluminium             13           26     Al
3     Silicon             14           28     Si
4  Phosphorus             15           30      P
5     Sulphur             16           32      S
6    Chlorine             17           34     Cl
7       Argon             18           36     Ar
8   Potassium             19           38      K
9     Calcium             20           40     Ca

In [19]:
dif.index=[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [20]:
dif

          Name  Atomic number  Mass Number Symbol
11      Sodium             11           22     Na
12   Magnesium             12           24     Mg
13   Aluminium             13           26     Al
14     Silicon             14           28     Si
15  Phosphorus             15           30      P
16     Sulphur             16           32      S
17    Chlorine             17           34     Cl
18       Argon             18           36     Ar
19   Potassium             19           38      K
20     Calcium             20           40     Ca

In [21]:
df

         Name  Atomic Number  Mass Number Symbol
1    Hydrogen              1            1      H
2      Helium              2            4     He
3     Lithium              3            6     li
4   Berrilium              4            8     Be
5       Boron              5           10      B
6      Carbon              6           12      C
7    Nitrogen              7           14      N
8      Oxygen              8           16      O
9    Flourine              9           18     Fl
10       Neon             10           20     Ne

In [22]:
dif

          Name  Atomic number  Mass Number Symbol
11      Sodium             11           22     Na
12   Magnesium             12           24     Mg
13   Aluminium             13           26     Al
14     Silicon             14           28     Si
15  Phosphorus             15           30      P
16     Sulphur             16           32      S
17    Chlorine             17           34     Cl
18       Argon             18           36     Ar
19   Potassium             19           38      K
20     Calcium             20           40     Ca

In [25]:
pd.concat([df, dif], ignore_index=True)

          Name  Atomic Number  Mass Number Symbol  Atomic number
0     Hydrogen            1.0            1      H            NaN
1       Helium            2.0            4     He            NaN
2      Lithium            3.0            6     li            NaN
3    Berrilium            4.0            8     Be            NaN
4        Boron            5.0           10      B            NaN
5       Carbon            6.0           12      C            NaN
6     Nitrogen            7.0           14      N            NaN
7       Oxygen            8.0           16      O            NaN
8     Flourine            9.0           18     Fl            NaN
9         Neon           10.0           20     Ne            NaN
10      Sodium            NaN           22     Na           11.0
11   Magnesium            NaN           24     Mg           12.0
12   Aluminium            NaN           26     Al           13.0
13     Silicon            NaN           28     Si           14.0
14  Phosphorus            NaN           30      P           15.0
15     Sulphur            NaN           32      S           16.0
16    Chlorine            NaN           34     Cl           17.0
17       Argon            NaN           36     Ar           18.0
18   Potassium            NaN           38      K           19.0
19     Calcium            NaN           40     Ca           20.0

In [27]:
df

         Name  Atomic Number  Mass Number Symbol
1    Hydrogen              1            1      H
2      Helium              2            4     He
3     Lithium              3            6     li
4   Berrilium              4            8     Be
5       Boron              5           10      B
6      Carbon              6           12      C
7    Nitrogen              7           14      N
8      Oxygen              8           16      O
9    Flourine              9           18     Fl
10       Neon             10           20     Ne

In [36]:
pd.concat([df, dif], ignore_index=True)

          Name  Atomic Number  Mass Number Symbol  Atomic number
0     Hydrogen            1.0            1      H            NaN
1       Helium            2.0            4     He            NaN
2      Lithium            3.0            6     li            NaN
3    Berrilium            4.0            8     Be            NaN
4        Boron            5.0           10      B            NaN
5       Carbon            6.0           12      C            NaN
6     Nitrogen            7.0           14      N            NaN
7       Oxygen            8.0           16      O            NaN
8     Flourine            9.0           18     Fl            NaN
9         Neon           10.0           20     Ne            NaN
10      Sodium            NaN           22     Na           11.0
11   Magnesium            NaN           24     Mg           12.0
12   Aluminium            NaN           26     Al           13.0
13     Silicon            NaN           28     Si           14.0
14  Phosphorus            NaN           30      P           15.0
15     Sulphur            NaN           32      S           16.0
16    Chlorine            NaN           34     Cl           17.0
17       Argon            NaN           36     Ar           18.0
18   Potassium            NaN           38      K           19.0
19     Calcium            NaN           40     Ca           20.0

In [37]:
pd.index = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]