In [1]:
import numpy as np
import pandas as pd

In [2]:
dict = {
    'Name' : ["Hydrogen", "Helium", "Lithium", "Berrilium", "Boron", "Carbon", "Nitrogen", "Oxygen", "Flourine", "Neon"],
    'Atomic Number' : [ 1, 2 , 3 , 4, 5, 6, 7, 8, 9, 10],
    'Mass Number' : [ 1.00, 4.00, 6.94, 9.01, 10.81, 12.01, 14.00, 15.99, 18.99, 20.17 ],
    'Symbol' : [ "H", "He", "li", "Be", "B", "C", "N", "O", "Fl", "Ne"]}

In [3]:
dit = { "Name" : ["Sodium", "Magnesium", "Aluminium", "Silicon", "Phosphorus", "Sulphur", "Chlorine","Argon", "Potassium", "Calcium"],
                            "Atomic Number" : [ 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
                            "Mass Number" : [ 22.98, 24.30, 26.98, 28.08	, 30.97, 32.06, 35.45, 39.94, 39.09, 40.07],
                            "Symbol" : [ "Na", "Mg", "Al", "Si", "P", "S", "Cl","Ar", "K", "Ca"]}

In [4]:
dit2 = {
    "Name" : ["Scandium", "Titanium", "Vanadium", "Chromium", "Magnese", "Iron", "Cobalt", "Nickel", "Copper", "Zinc", "Galium", "Germanium", "Arsenic", "Selenum", "Bromine", "Krypton", "Rubidium", "Strontium", "Yttrium", "Zirconium"],
    "Atomic Number" : [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40 ],
    "Mass Number" : [44.95, 47.86, 50.94, 51.99, 54.93, 55.84, 58.93, 58.69, 63.54, 65.39, 69.72, 72.64, 74.92, 78.96, 79.90, 83.79, 85.46, 87.62, 88.90, 91.22 ],
    "Symbol" : [ "Sc", "Ti", "V", "Cr", "Mn","Fe", "Co", "Ni", "Cu", "Zn","Ga", "Ge", "As", "Se", "Br", "Kr", "Rb", "Sr", "Y", "Zr"]
    
}

In [5]:
df = pd.DataFrame(dict)
dif = pd.DataFrame(dit)
dif2 = pd.DataFrame(dit2)

In [6]:
df, dif, dif2

(        Name  Atomic Number  Mass Number Symbol
 0   Hydrogen              1         1.00      H
 1     Helium              2         4.00     He
 2    Lithium              3         6.94     li
 3  Berrilium              4         9.01     Be
 4      Boron              5        10.81      B
 5     Carbon              6        12.01      C
 6   Nitrogen              7        14.00      N
 7     Oxygen              8        15.99      O
 8   Flourine              9        18.99     Fl
 9       Neon             10        20.17     Ne,
          Name  Atomic Number  Mass Number Symbol
 0      Sodium             11        22.98     Na
 1   Magnesium             12        24.30     Mg
 2   Aluminium             13        26.98     Al
 3     Silicon             14        28.08     Si
 4  Phosphorus             15        30.97      P
 5     Sulphur             16        32.06      S
 6    Chlorine             17        35.45     Cl
 7       Argon             18        39.94     Ar
 8   Potassium             19        39.09      K
 9     Calcium             20        40.07     Ca,
          Name  Atomic Number  Mass Number Symbol
 0    Scandium             21        44.95     Sc
 1    Titanium             22        47.86     Ti
 2    Vanadium             23        50.94      V
 3    Chromium             24        51.99     Cr
 4     Magnese             25        54.93     Mn
 5        Iron             26        55.84     Fe
 6      Cobalt             27        58.93     Co
 7      Nickel             28        58.69     Ni
 8      Copper             29        63.54     Cu
 9        Zinc             30        65.39     Zn
 10     Galium             31        69.72     Ga
 11  Germanium             32        72.64     Ge
 12    Arsenic             33        74.92     As
 13    Selenum             34        78.96     Se
 14    Bromine             35        79.90     Br
 15    Krypton             36        83.79     Kr
 16   Rubidium             37        85.46     Rb
 17  Strontium             38        87.62     Sr
 18    Yttrium             39        88.90      Y
 19  Zirconium             40        91.22     Zr)

In [7]:
dif3 = pd.concat([df, dif, dif2], ignore_index = True)

In [8]:
dif3.index = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40]

In [9]:
dif3

          Name  Atomic Number  Mass Number Symbol
1     Hydrogen              1         1.00      H
2       Helium              2         4.00     He
3      Lithium              3         6.94     li
4    Berrilium              4         9.01     Be
5        Boron              5        10.81      B
6       Carbon              6        12.01      C
7     Nitrogen              7        14.00      N
8       Oxygen              8        15.99      O
9     Flourine              9        18.99     Fl
10        Neon             10        20.17     Ne
11      Sodium             11        22.98     Na
12   Magnesium             12        24.30     Mg
13   Aluminium             13        26.98     Al
14     Silicon             14        28.08     Si
15  Phosphorus             15        30.97      P
16     Sulphur             16        32.06      S
17    Chlorine             17        35.45     Cl
18       Argon             18        39.94     Ar
19   Potassium             19        39.09      K
20     Calcium             20        40.07     Ca
21    Scandium             21        44.95     Sc
22    Titanium             22        47.86     Ti
23    Vanadium             23        50.94      V
24    Chromium             24        51.99     Cr
25     Magnese             25        54.93     Mn
26        Iron             26        55.84     Fe
27      Cobalt             27        58.93     Co
28      Nickel             28        58.69     Ni
29      Copper             29        63.54     Cu
30        Zinc             30        65.39     Zn
31      Galium             31        69.72     Ga
32   Germanium             32        72.64     Ge
33     Arsenic             33        74.92     As
34     Selenum             34        78.96     Se
35     Bromine             35        79.90     Br
36     Krypton             36        83.79     Kr
37    Rubidium             37        85.46     Rb
38   Strontium             38        87.62     Sr
39     Yttrium             39        88.90      Y
40   Zirconium             40        91.22     Zr

In [13]:
dif3.to_numpy()

array([['Hydrogen', 1, 1.0, 'H'],
       ['Helium', 2, 4.0, 'He'],
       ['Lithium', 3, 6.94, 'li'],
       ['Berrilium', 4, 9.01, 'Be'],
       ['Boron', 5, 10.81, 'B'],
       ['Carbon', 6, 12.01, 'C'],
       ['Nitrogen', 7, 14.0, 'N'],
       ['Oxygen', 8, 15.99, 'O'],
       ['Flourine', 9, 18.99, 'Fl'],
       ['Neon', 10, 20.17, 'Ne'],
       ['Sodium', 11, 22.98, 'Na'],
       ['Magnesium', 12, 24.3, 'Mg'],
       ['Aluminium', 13, 26.98, 'Al'],
       ['Silicon', 14, 28.08, 'Si'],
       ['Phosphorus', 15, 30.97, 'P'],
       ['Sulphur', 16, 32.06, 'S'],
       ['Chlorine', 17, 35.45, 'Cl'],
       ['Argon', 18, 39.94, 'Ar'],
       ['Potassium', 19, 39.09, 'K'],
       ['Calcium', 20, 40.07, 'Ca'],
       ['Scandium', 21, 44.95, 'Sc'],
       ['Titanium', 22, 47.86, 'Ti'],
       ['Vanadium', 23, 50.94, 'V'],
       ['Chromium', 24, 51.99, 'Cr'],
       ['Magnese', 25, 54.93, 'Mn'],
       ['Iron', 26, 55.84, 'Fe'],
       ['Cobalt', 27, 58.93, 'Co'],
       ['Nickel', 28, 58.69, 'Ni'],
       ['Copper', 29, 63.54, 'Cu'],
       ['Zinc', 30, 65.39, 'Zn'],
       ['Galium', 31, 69.72, 'Ga'],
       ['Germanium', 32, 72.64, 'Ge'],
       ['Arsenic', 33, 74.92, 'As'],
       ['Selenum', 34, 78.96, 'Se'],
       ['Bromine', 35, 79.9, 'Br'],
       ['Krypton', 36, 83.79, 'Kr'],
       ['Rubidium', 37, 85.46, 'Rb'],
       ['Strontium', 38, 87.62, 'Sr'],
       ['Yttrium', 39, 88.9, 'Y'],
       ['Zirconium', 40, 91.22, 'Zr']], dtype=object)

In [14]:
type(dif3)

pandas.DataFrame

In [15]:
dif3.T

,1,2,3,4,5,6,7,8,9,10,...,31,32,33,34,35,36,37,38,39,40
Name,Hydrogen,Helium,Lithium,Berrilium,Boron,Carbon,Nitrogen,Oxygen,Flourine,Neon,...,Galium,Germanium,Arsenic,Selenum,Bromine,Krypton,Rubidium,Strontium,Yttrium,Zirconium
Atomic Number,1,2,3,4,5,6,7,8,9,10,...,31,32,33,34,35,36,37,38,39,40
Mass Number,1.0,4.0,6.94,9.01,10.81,12.01,14.0,15.99,18.99,20.17,...,69.72,72.64,74.92,78.96,79.9,83.79,85.46,87.62,88.9,91.22
Symbol,H,He,li,Be,B,C,N,O,Fl,Ne,...,Ga,Ge,As,Se,Br,Kr,Rb,Sr,Y,Zr

In [16]:
dif3.head(5)

        Name  Atomic Number  Mass Number Symbol
1   Hydrogen              1         1.00      H
2     Helium              2         4.00     He
3    Lithium              3         6.94     li
4  Berrilium              4         9.01     Be
5      Boron              5        10.81      B

In [17]:
dif3.tail(8)

         Name  Atomic Number  Mass Number Symbol
33    Arsenic             33        74.92     As
34    Selenum             34        78.96     Se
35    Bromine             35        79.90     Br
36    Krypton             36        83.79     Kr
37   Rubidium             37        85.46     Rb
38  Strontium             38        87.62     Sr
39    Yttrium             39        88.90      Y
40  Zirconium             40        91.22     Zr

In [18]:
dif3.loc()